dist: bionic
language: common-lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  - sudo apt-get install info install-info libturbojpeg0-dev
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^#cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi
  - cl -e '(ql-util:without-prompting (ql:add-to-init-file))'

before_script:
  - mkdir lisp
  - pushd lisp
  - git clone --depth 1 git://github.com/shamazmazum/imago.git
  - git clone --depth 1 git://github.com/shamazmazum/vp-trees.git
  - git clone --depth 1 git://github.com/shamazmazum/perceptual-hashes.git
  - popd

script:
  - cl -f $TRAVIS_BUILD_DIR/tests/travis.lisp
